#!/bin/bash

# Скрипт для исправления ошибки сборки iOS проекта Flutter
# Ошибка: Command PhaseScriptExecution failed with a nonzero exit code

echo "🔧 Начинаю исправление ошибки сборки iOS..."

# Определяем корневую директорию проекта
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$SCRIPT_DIR"
IOS_DIR="$PROJECT_ROOT/ios"

cd "$PROJECT_ROOT"

# 1. Очистка кеша Flutter
echo "📦 Очищаю кеш Flutter..."
flutter clean

# 2. Удаление старых Pods
echo "🗑️  Удаляю старые Pods..."
rm -rf Pods
rm -rf Podfile.lock
rm -rf .symlinks
rm -rf Flutter/Flutter.framework
rm -rf Flutter/Flutter.podspec

# 3. Получение зависимостей Flutter
echo "📥 Получаю зависимости Flutter..."
flutter pub get

# 4. Обновление CocoaPods
echo "☕ Обновляю CocoaPods..."
cd "$IOS_DIR"
pod repo update

# 5. Установка Pods
echo "📦 Устанавливаю Pods..."
pod install --repo-update
cd "$PROJECT_ROOT"

# 6. Проверка прав доступа к скриптам
echo "🔐 Проверяю права доступа..."
chmod +x "${PWD}/Flutter/ephemeral/flutter_export_environment.sh" 2>/dev/null || true

# 7. Очистка DerivedData Xcode
echo "🧹 Очищаю DerivedData Xcode..."
rm -rf ~/Library/Developer/Xcode/DerivedData/*

# 8. Исправление проблем с define flags в Pods
echo "🔧 Исправляю проблемы с define flags..."
cd "$IOS_DIR"
if [ -d "Pods" ]; then
  # Ищем и исправляем проблемы в файлах xcconfig Pods
  # Удаляем пробелы в конце строк
  find Pods/Target\ Support\ Files -name "*.xcconfig" -type f -exec sed -i '' 's/[[:space:]]*$//' {} \; 2>/dev/null || true
  # Убираем лишние пробелы вокруг знака =
  find Pods/Target\ Support\ Files -name "*.xcconfig" -type f -exec sed -i '' 's/[[:space:]]*=[[:space:]]*/=/' {} \; 2>/dev/null || true
  # Исправляем дублирующиеся $(inherited) в GCC_PREPROCESSOR_DEFINITIONS и других строках
  # Заменяем " $(inherited) $(inherited)" на " $(inherited)"
  find Pods/Target\ Support\ Files -name "*.xcconfig" -type f -exec sed -i '' 's/\$(inherited)[[:space:]]\+COCOAPODS=1[[:space:]]\+\$(inherited)/$(inherited) COCOAPODS=1/g' {} \; 2>/dev/null || true
  # Удаляем дублирующиеся $(inherited) в любых местах
  find Pods/Target\ Support\ Files -name "*.xcconfig" -type f -exec sed -i '' 's/\$(inherited)[[:space:]]\+\$(inherited)/$(inherited)/g' {} \; 2>/dev/null || true
fi
cd "$PROJECT_ROOT"

# 9. Очистка build директории iOS
echo "🧹 Очищаю build директорию iOS..."
rm -rf "$IOS_DIR/build"

# 10. Создание flutter_export_environment.sh если отсутствует
echo "📝 Проверяю flutter_export_environment.sh..."
cd "$IOS_DIR/Flutter"
if [ ! -f "ephemeral/flutter_export_environment.sh" ]; then
  mkdir -p ephemeral
  echo '#!/bin/sh
# This file is generated by Flutter
export FLUTTER_ROOT="$FLUTTER_ROOT"
export FLUTTER_APPLICATION_PATH="$FLUTTER_APPLICATION_PATH"
export FLUTTER_TARGET="$FLUTTER_TARGET"
export FLUTTER_BUILD_DIR="$FLUTTER_BUILD_DIR"
export FLUTTER_BUILD_NAME="$FLUTTER_BUILD_NAME"
export FLUTTER_BUILD_NUMBER="$FLUTTER_BUILD_NUMBER"
' > ephemeral/flutter_export_environment.sh
  chmod +x ephemeral/flutter_export_environment.sh
fi
cd "$PROJECT_ROOT"

echo ""
echo "✅ Готово! Теперь попробуйте собрать проект снова:"
echo "   flutter build ios"
echo "   или откройте Runner.xcworkspace в Xcode и соберите там"

